### ISSUE TITLE
HTML大枠作成

### ISSUE THREAD

**Issue by kakudaisuke** [WebYorozuya/jazz-review#1]
#要件
全ページ共通となるHTML(index.html)の大枠を作る

#タスク
- [x] ヘッダー、フッター
- [x] ３カラム
- [ ] サイトロゴ
- [x] CSS読み込み
- [x] 右上のユーザー表示はとりま`<p>ゲストさん</p>`とかで

**Comment by ghost** [comment]
@kakudaisuke 
検索窓不要について、認識の相違が出そうなのでもう少し教えていただきたいです。

**Comment by kakudaisuke** [comment]
@mike3104 ごめんなさい。CSS、検索窓不要の意味を僕も完全に忘れてしまいました。修正します。
