### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by kakudaisuke** [WebYorozuya/jazz-review#3]
#要件
DBの設計をする

#タスク
- [x] 必要なテーブル、カラム、他のテーブルとの関連を洗い出す
- [x] 適切な名称を検討する
- [x] 複数人でDBを共有するにはどうすれば？？

**Comment by tuka1031** [comment]
@kakudaisuke 
午前中はちょっと本業でやることがあるので、午後から必要なテーブル、カラム、他のテーブルとのER図を書いていきます。
終わったら、共有します。
