### ISSUE TITLE
デザインのブラッシュアップ（逐次追加お願いします）

### ISSUE THREAD

**Issue by kakudaisuke** [WebYorozuya/jazz-review#341]
- [ ] 正式ロゴ
- [ ] ユーザードロップダウンメニュー
- [ ] 投稿ドロップダウンメニュー
- [x] いいねのかわいいアニメーション
- [x] タイトルが２行に渡る時のスタイル
- [ ] 
- [ ]  
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by uekiGityuto** [comment]
closeしますー
